#
# Copyright (C) 2017 XLAB, Ltd.
# Copyright (C) 2018 Waldemar Kozaczuk
#
# This work is open source software, licensed under the terms of the
# BSD license as described in the LICENSE file in the top-level directory.
#
# This Docker file defines a container intended to run and test OSv
# It comes with capstan that can pull kernel and pre-built MPM packages
#
ARG DIST_VERSION=22.04
FROM ubuntu:${DIST_VERSION}

ENV DEBIAN_FRONTEND noninteractive
ENV TERM=linux

RUN mkdir -p /root/.config/gdb && echo "add-auto-load-safe-path /git-repos/osv/scripts/loader.py" > /root/.config/gdb/gdbinit

#COPY ./etc/keyboard /etc/default/keyboard
#COPY ./etc/console-setup /etc/default/console-setup

RUN apt-get update -y && apt-get install -y \
git \
build-essential \
g++-10 \
python3 \
curl \
qemu-system-x86 \
qemu-utils \
libaio-dev \
vim \
ack
RUN apt install -y wget

# - prepare directories
RUN mkdir /git-repos

# - clone OSv
#WORKDIR /git-repos
#ARG GIT_ORG_OR_USER=Meandres
#RUN git clone https://github.com/${GIT_ORG_OR_USER}/osv.git

#WORKDIR /git-repos/osv
#RUN git submodule update --init --recursive
#RUN ./scripts/setup.py

# - add vmcache
#WORKDIR /git-repos
#RUN git clone https://github.com/Meandres/vmcache.git
#RUN cd vmcache && make 

# - add exmap
#WORKDIR /git-repos
#RUN git clone https://github.com/tuhhosg/exmap.git

WORKDIR /git-repos
RUN wget http://nz2.archive.ubuntu.com/ubuntu/pool/main/o/openssl/libssl1.1_1.1.1f-1ubuntu2_amd64.deb
RUN dpkg -i libssl1.1_1.1.1f-1ubuntu2_amd64.deb

CMD /bin/bash

#
# NOTES
#
# Build the container example:
# docker build -t osv/runner-ubuntu -f Dockerfile.runner-ubuntu .
#
# Build the container based of specific Ubuntu version and git repo owner (if forked) example:
# docker build -t osv/runner-ubuntu -f Dockerfile.runner-ubuntu --build-arg DIST_VERSION=20.04 --build-arg GIT_ORG_OR_USER=a_user .
#
# Run the container FIRST time example:
# docker run -it --privileged osv/runner-ubuntu
#
# To restart:
# docker restart ID (from docker ps -a) && docker attach ID
#
# To open in another console:
# docker exec -it ID /bin/bash
